version: '3.8'

services:
  mongo: 
    image: mongo:6.0
    container_name: mse-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_app_db
    volumes:
      - mongo_data:/data/db # Volume lưu data MongoDB
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  rabbitmq:
    image: rabbitmq:management
    container_name: mse-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/ # THAY THẾ volume CŨ
      
volumes:
  mongo_data: # Volume cho MongoDB
  rabbitmq_data: # Volume cho RabbitMQdocker-compose up -d mongo rabbitmq