/**
 * Error codes constants
 */
const ERROR_CODES = {
	// General
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	NOT_FOUND: 'NOT_FOUND',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	INTERNAL_ERROR: 'INTERNAL_ERROR',

	// Auth
	AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
	AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
	AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
	AUTH_REQUIRED: 'AUTH_REQUIRED',

	// User
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
	USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',

	// Device
	DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
	DEVICE_INSUFFICIENT_QUANTITY: 'DEVICE_INSUFFICIENT_QUANTITY',
	DEVICE_ALREADY_EXISTS: 'DEVICE_ALREADY_EXISTS',

	// Borrow
	BORROW_TICKET_NOT_FOUND: 'BORROW_TICKET_NOT_FOUND',
	BORROW_INVALID_STATUS: 'BORROW_INVALID_STATUS',
	BORROW_ALREADY_RETURNED: 'BORROW_ALREADY_RETURNED',

	// Category
	CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
	CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
	CATEGORY_IN_USE: 'CATEGORY_IN_USE',
};

const ERROR_MESSAGES = {
	[ERROR_CODES.VALIDATION_ERROR]: 'Dữ liệu không hợp lệ',
	[ERROR_CODES.NOT_FOUND]: 'Không tìm thấy',
	[ERROR_CODES.UNAUTHORIZED]: 'Chưa đăng nhập',
	[ERROR_CODES.FORBIDDEN]: 'Không có quyền truy cập',
	[ERROR_CODES.INTERNAL_ERROR]: 'Lỗi hệ thống',
	[ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Email hoặc mật khẩu không đúng',
	[ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Token đã hết hạn',
	[ERROR_CODES.AUTH_TOKEN_INVALID]: 'Token không hợp lệ',
	[ERROR_CODES.AUTH_REQUIRED]: 'Yêu cầu đăng nhập',
	[ERROR_CODES.USER_NOT_FOUND]: 'Không tìm thấy người dùng',
	[ERROR_CODES.USER_ALREADY_EXISTS]: 'Người dùng đã tồn tại',
	[ERROR_CODES.USER_EMAIL_EXISTS]: 'Email đã được sử dụng',
	[ERROR_CODES.DEVICE_NOT_FOUND]: 'Không tìm thấy thiết bị',
	[ERROR_CODES.DEVICE_INSUFFICIENT_QUANTITY]: 'Số lượng thiết bị không đủ',
	[ERROR_CODES.DEVICE_ALREADY_EXISTS]: 'Thiết bị đã tồn tại',
	[ERROR_CODES.BORROW_TICKET_NOT_FOUND]: 'Không tìm thấy phiếu mượn',
	[ERROR_CODES.BORROW_INVALID_STATUS]: 'Trạng thái phiếu mượn không hợp lệ',
	[ERROR_CODES.BORROW_ALREADY_RETURNED]: 'Phiếu mượn đã được trả',
	[ERROR_CODES.CATEGORY_NOT_FOUND]: 'Không tìm thấy danh mục',
	[ERROR_CODES.CATEGORY_ALREADY_EXISTS]: 'Danh mục đã tồn tại',
	[ERROR_CODES.CATEGORY_IN_USE]: 'Danh mục đang được sử dụng',
};

const getErrorMessage = (code, defaultMessage = 'Có lỗi xảy ra') => {
	return ERROR_MESSAGES[code] || defaultMessage;
};

module.exports = {
	ERROR_CODES,
	ERROR_MESSAGES,
	getErrorMessage,
};

